[package]
name = "termviz"
version = "0.1.1"
authors = ["Carsten Zumsande <termviz@zumsande.eu>", "Emanuele Palazzolo <emanuele.palazzolo@gmail.com>", "Michael Maerz <michael0maerz@gmail.com>"]
edition = "2018"
license = "MIT"
exclude = ["assets/*", ".github"]
description = "ROS visualization on the terminal"

[dependencies]
approx = "0.5.1"
byteorder = "*"
chrono = "0.2.25"
clap = "*"
colorgrad = "*"
crossterm = { version = '0.23', features = ["event-stream"] }
futures = "0.3"
futures-timer = "3.0"
image = "0.24.6"
nalgebra = ">=0.29.0"
rand = "0.8.5"
rosrust = "0.9.11"
rosrust_msg = "0.1.7"
rustros_tf = { git = "https://github.com/maximaerz/rustros_tf" }
serde = { version = "*", features = ["derive"] }
serde_derive = "*"
strum = "0.23"
strum_macros = "0.23"
timer = "0.1.6"
tokio = { version = "1.16", features = ["full"] }
tui = "0.18.0"
tui-image = { git = "https://github.com/arraypad/tui-image", version = "*" }

[dependencies.confy]
version = "0.5.0"
features = ["yaml_conf"]
default-features = false

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"

