[package]
name = "termviz"
version = "0.1.0"
authors = ["Carsten Zumsande <termviz@zumsande.eu>"]
edition = "2018"
license = "MIT"
exclude = ["assets/*", ".github"]


[dependencies]
nalgebra = "*"
rosrust = "0.9"
rosrust_msg = "0.1"
rustros_tf = { git = "https://github.com/maximaerz/rustros_tf" }
serde = { version = "*", features = ["derive"] }
serde_derive = "*"
termion = "1.5"
tui = "0.10.0"

[dependencies.confy]
version = "0.4.0"
features = ["yaml_conf"]
default-features = false

[patch.crates-io]
confy = { git = 'https://github.com/rust-cli/confy' }
